### ISSUE TITLE
arrowheads is not a function

### ISSUE THREAD

**Issue by Mattperkinsee** [slutske22/leaflet-arrowheads#3]
Trying to import this. Had to add` type="module" ` to `<script type="module" src="/iStats/js/leaflet-arrowheads.js"></script>` and change the import path inside it to `import { } from './leaflet.geometryutil.js'`. Now I'm getting `L.polyline(...).arrowheads is not a function` 
Any idea what the problem is?

**Comment by slutske22** [comment]
It sounds like you're trying to link leaflet-arrowheads directly from your HTML header, as opposed to importing it directly into your own module?  Yes I realized in another thread that if you're trying to link leaflet-arrowheads.js directly from your HTML header, you need to delete the import and export statements, and just put the `<script src="...leaflet.geometryutil.js></script>` in your HTML header somewhere before the `<script src="...leaflet-arrowheads.js"></script>`.  Then you don't need to import it into your own script file, as its already loaded on the page.  Also, you are indeed typing `L.polyline(...).arrowheads()`, not just `L.polyline(...).arrowheads`, correct?

I'll leave this issue open for now as a reminder to make some adjustments so that leaflet-arrowheads is ready fresh out of the box for use directly in the HTML header as well as with modules.  Feel free to give feedback on how I can adjust the code for this purpose, or open a PR.

Thanks,
~S

**Comment by Shkarface** [comment]
I have the same issue here but with geojson polylines

**Comment by slutske22** [comment]
Can you post your code about how you are linking leaflet.arrowheads into your project?

**Comment by manzanotti** [comment]
I don't know if this helps, but I had this issue when I was referencing the arrowheads file on a CDN directly in my HTML.

So, I added a script tag for leaflet.geometryutil.min.js on a CDN, then changed the script tag for arrowheads to request leaflet-arrowheads.js rather than index.js.

This solved the issue.

To be absolutely clear, I am including everything to do with leaflet in script tags, all from CDNs. This means that parcel.js isn't trying to pull them in, but the functions required are there in the javascript on the deployed site. I do have intellisense errors still, though I'm assuming this is because my code is in Typescript, and there isn't a typings file for arrowheads, but parcel.js happily builds the project, and the site works.
