### ISSUE TITLE
Leaflet 1.9.1 does not include L.GeometryUtil

### ISSUE THREAD

**Issue by Concequence** [slutske22/leaflet-arrowheads#31]
Recently updated to Leaflet 1.9.1 and the L object does not have GeometryUtil, which this package relies on to work. 
I could not find a way to get this working without just downgrading Leaflet. 

Also do you plan to update this for React 17/18 ?

**Comment by slutske22** [comment]
Hmmmm, I have not tried this with 1.9 yet, but I imagine the removal of the `L` global in leaflet 1.9 is going to cause alot of problems with tons of plugins in the leaflet ecosystem.  The [1.9 release notes](https://github.com/Leaflet/Leaflet/releases/tag/v1.9.0) do mention 

> we will provide a shim that can be imported manually that will restore this functionality

Though I have no idea when that will happen.  Ultimately this problem is upstream, with leaflet-geometryutil and leaflet itself.  But, it does bother me, so there's a pretty simple shim you can do yourself to get this working with leaflet ^1.9

Install leaflet-geometryutil as a dependency of your project

```
npm i leaflet-geometryutil
```

When you import 'leaflet-arrowheads', attach `GeometryUtil` to `L` yourself:

```
import L from "leaflet";
import "leaflet-arrowheads";
import GeometryUtil from "leaflet-geometryutil";

L.GeometryUtil = GeometryUtil;
```

Seems to work fine

## [codesandbox example](https://codesandbox.io/s/leaflet-arrowheads-example-leaflet-1-9-js49jp?file=/src/index.js:23-157)

**Comment by manzanotti** [comment]
I think they've reversed the change in 1.9.2

https://github.com/Leaflet/Leaflet/pull/8493

**Comment by slutske22** [comment]
Thank goodness
