### ISSUE TITLE
Performance issue with LineString containig 10k+ coordinates

### ISSUE THREAD

**Issue by lukasxrv** [slutske22/leaflet-arrowheads#32]
It has a performance problem when using arrows on L.geoJSON containing a LineString with 10,000 or more coordinates.
After zooming in on the map for a detailed view, all the arrows are apparently calculated, even if they are not in the viewport. The browser is at 100% CPU for tens of seconds.

**Comment by slutske22** [comment]
This is because when applying `.arrowheads()`, the polyline's `options.noClip` is deliberately set to true.  The reason for this is that if noClip remains `false`, the portions of the parent polyline that are off screen will not be drawn.  leaflet-arrowheads uses the actual *drawn* portions to render the arrowheads, not the original latlng coordinates.  So with noClip as false, your arrowheads may not render as expected.

That being said, you can override this behavior with a few extra lines of code.  If you are rendering from geojson:

```js
const geojsonExample = L.geoJSON(yourGeoJSON, {
  arrowheads: {},
  onEachFeature: function (f, layer) {
    layer.options.noClip = false;            // <---------------- you need this here
  }
})
  .addTo(map);
```

This way, when leaflet transforms your geojson into leaflet geometries, it sets the `noClip` back to false.

I'm not sure what your use case is, but even without arrowheads, you're going to need to find some methods to optimize map rendering when working with 10k+ points.  I'm also not sure how useful arrowheads would be with so many points from a UX perspective.  But that code should at least solve your described issue.

**Comment by janpalas** [comment]
Thanks for the suggested solution, we will definitely try that (I'm a colleague of @lukasxrv)!

Our use case: We do GPS monitoring of (agriculture) vehicles, thus we display routes of these vehicles. In agriculture, it is common that you have very long rides, sometimes even between duration of 9-12 hours. A route of such a ride has the mentioned 10K+ points, even if we apply some simplification of the route.

Interestingly, when displaying such a route with arrowheads, the map is slow even when you pan around places where there are no points of the route visible... (When we switch of arrowheads, the map behaves OK, even with such complicated routes.)

**Comment by slutske22** [comment]
@janpalas yes that makes sense, because as I said above, `noClip` is set to true when you apply arrowheads.  So that means that even if the route of offscreen, leaflet will still render it, meaning your CPU is doing all that work, even when its offscreen. Hopfefully the code suggestion helps you guys.

> We do GPS monitoring of (agriculture) vehicles, thus we display routes of these vehicles

Sounds cool.  You guys hiring?

**Comment by lukasxrv** [comment]
I tried set `noClip = false` as @slutske22 mentioned. It seems, it has just right effect as we needed. Thanks, it looks good. We will do some tests, to ensure that we can use it.
