### ISSUE TITLE
removeLayer issue

### ISSUE THREAD

**Issue by gil-game-sh** [slutske22/leaflet-arrowheads#7]
Hi slutske22, thanks for this plugin.

I  want to draw a temporary arrow, updated and changed periodically. In my periodic callback I do :
```
  if(arrow !== undefined)
  {
    mymap.removeLayer(arrow);
   }
  arrow = L.polyline([ [from.lat, from.lng],[to.lat, to.lng] ]).arrowheads().addTo(mymap);

```
But the redraw caused by the removeLayer remove the main polyline part but not the arrow part.
Do you have an idea ?

**Comment by slutske22** [comment]
You'll have to use `arrow.remove()` instead of `mymap.removeLayer(arrow)`.  This plugin alters the `L.Polyline.remove` method to remove a polyline's associated arrowheads (if they exist) when the polyline itself is removed from the map.  The `L.Map.removeLayer` method does not.  

Try that and et me know if you're still having issues.
